### ISSUE TITLE
Lab 5

### ISSUE THREAD

**Issue by AtaiDobrynin** [Natarov-Ilya/Natarov_Robot#1]
Нету новых целей, они не движутся, перезапуска игры нет.
Стиль кода ужасен, функции стоят вперемешку с основным кодом
Не вычеркнуты globalы

**Comment by Natarov-Ilya** [comment]
Спасибо, постараюсь переделать на следующих выходных, раньше вообще никак - дел выше крыши. Правильно понял что это к пушке относится? Какие оценки за остальные лабы?

- -
С уважением,
Илья

вторник, 10 декабря 2019 г., 0:25 +0300 от notifications@github.com  <notifications@github.com>:
